version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        description: greenweez raw data
        identifier: raw_gz_product
      - name: sales
        description: information regarding our sales
        freshness: 
          warn_after: {count: 90, period: days}  
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier: raw_gz_sales
        tests: 
            - unique:
              column_name: "(orders_id || _ || pdt_id)"
      - name: ship
        description: information regarding our shipping costs
        identifier: raw_gz_ship